/*
  Generated by generator https://github.com/mrhieu/generator
*/

class {Name}Ctrl {
  constructor() {
    'ngInject';

    this.name = '{Name}';
  }

  $onInit() {

  }
}

export default {Name}Ctrl
